### PR TITLE
Move Core Data Logic

### PR DESCRIPTION
**Pull request by gyasistory**
- Re Organize Library to follow a more Standard convention
- Add CoreData Model from MPDX
- Create Data Object from coreData

### CODE REVIEW

**Comment by frett** [comment]
why are you committing the Pods to the git repo?

**Comment by levieggertcru** [comment]
Hey @gyasistory just curious what your plan of attack is on this PR.  
I noticed you moved the CoreData model and it auto generated the CoreData entity classes.  Are you going to move any of the MPDX CoreData implementations over in this PR?

**Comment by gyasistory** [comment]
> why are you committing the Pods to the git repo?

@frett can you clarify I am not quite sure what you are asking?

**Comment by gyasistory** [comment]
> Hey @gyasistory just curious what your plan of attack is on this PR. I noticed you moved the CoreData model and it auto generated the CoreData entity classes. Are you going to move any of the MPDX CoreData implementations over in this PR?

@levieggertcru You have to store the core data file and the swift file in a separate location.  This was only the first step my only goal was to move the core data in the pod.

**Comment by levieggertcru** [comment]
Hey @gyasistory so far looks good to me.  I think Daniel was talking about the Pods under the Example folder and making sure that is added to the .gitignore so they aren't checked into the repo.

**Comment by frett** [comment]
Also Pods for the library itself. For example, you are commiting the CoreData pod in the root Pods directory

**Review by levieggertcru — APPROVED** [review]

**Pull request merged**
